### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by edvorg** [hraberg/deuce#21]
Hello, I'm very interested in that project and I see that it's a bit stuck at this point.
What if look and this attempt from other point of view.
What if we create a clojure to emacs lisp compiler and make it work integrated with emacs ecosystem as much as possible?
It could be much more easier task, and also will free us from distraction of re-implementing some very low level emacs stuff.

**Comment by edvorg** [comment]
So this task could be split in two parts.
1) clojure -> elisp compiler
2) optional - reimplement emacs elisp core to run clojure itself without compilation to elisp

**Comment by edvorg** [comment]
The main reason I suggest such roadmap is simple - we could get something working much faster, we will see if this all works at all and whether anybody interested in it or not. Once we pass first step, we could start working on elisp -> clojure switch and on elisp -> clojure compilation.

**Comment by hraberg** [comment]
Hi Edward.

What you're suggesting is on my radar, see one of my other projects:
https://github.com/hraberg/cljs2go

I've considered writing an Emacs Lisp backend for ClojureScript as ClojureScript is now self-hosting (in the past this made less sense) and done some minor investigations about what it would entail on the Emacs Lisp side for protocols etc.

Originally the goal of Deuce was getting rid of the C parts of Emacs and replace them with the JVM and Clojure. One drawback with this approach is that it's a lot of work to replicate the Emacs runtime (implementing Emacs Lisp is the "easy" part) and a lot of baggage from Emacs comes with that (like prevalent use of mutability for example), so the result is still not very idiomatic Clojure 

Happy to bounce ideas, the main issue is that ClojureScript doesn't support pluggable backends, like cljs2go there are many dead forks of ClojureScript to interesting targets, so in theory one should start there and add this support - which would require convincing David (and the ClojureScript team), as it complicates the existing JavaScript compiler.

Another broader reason this project is stalled is the EPL vs GPL issue, see #20.

**Comment by interstar** [comment]
Have you looked at Pixie? https://github.com/pixie-lang/pixie

A Clojure-like language targetting the PyPy toolchain that compile
natively. I wonder if that's easier to make plugable back-ends for.

Phil

**Comment by hraberg** [comment]
Hi Phil,

I've looked at Pixie in the past (not in relation to Deuce), and the idea is nice - but my impression is that it's pretty tied to RPython.

ClojureScript is relatively easy to port (as the many forks show) to new backends, and contains an (almost) pure Clojure implementation of clojure.core (including the persistent data structures) and the analyser and compiler. The main issue is that the a fork is hard to keep in sync.

Emacs 25 will support dynamic modules (written in C), so in theory one could try to embed Clojure JVM proper in Emacs itself, see:
https://github.com/syohex/emacs-mruby-test
http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html

**Comment by edvorg** [comment]
Why not propose ClojureScript pluggable backends for GSOC 2016?

**Comment by hraberg** [comment]
Great idea! It would be great for the Clojure ecosystem I think. Not sure I myself have the time to take it on though.

**Comment by edvorg** [comment]
I could probably find a time for some help, but I'm not sure I have enough of relevant experience. I created a discussion on clojure mailing list. https://groups.google.com/forum/#!topic/clojure/xabJ0f9O_HI 
Let's see, what people say.

**Comment by hraberg** [comment]
Cool, had a look at the thread. The tools analyzer stuff is interesting - but one part that's easy to forget is that ClojureScript contains clojure.core and its backing types written in Clojure, which really lowers the bar to porting. When I wrote cljs.go I wanted to base it on the tools.analyzer stuff, but ClojureScript was more straight forward to get a full working system from.

The analyzer and compiler is almost easier to write from scratch than replicating the core libraries. In a way, these are two different problems, conflated due to ClojureScript currently containing -almost- the solution for both :-)

To compare with Deuce, it stalled mainly due to the vast amount of Emacs functionality needed to run Emacs, not due to the complexity of replicating Emacs Lisp itself.

**Comment by hraberg** [comment]
Closing as the conversation ended. Again, see #20 for the real blocker.

Shen was recently ported to Emacs Lisp which might be of interest to anyone wanting to write a Clojure/Script Emacs Lisp backend:
https://github.com/deech/shen-elisp

**Comment by hraberg** [comment]
Implementing an Emacs Lisp backend for Clojure/Script was also discussed in #2.
