### ISSUE TITLE
How far away is this from being an emacs replacement?

### ISSUE THREAD

**Issue by SlightlyCyborg** [hraberg/deuce#22]

**Comment by hraberg** [comment]
Pretty far. The first step would be to just make it a working (but not necessarily usable) editor which supports a subset of Emacs. At this point it's still pretty far from being an actual Emacs replacement.

Apart from the work of simply making it compatible, making it fast and usable is kind of an orthogonal concern, the best bet is to turn it into a server, or simply ditch the Emacs compatibility.

As mentioned elsewhere, I might write a Zile clone embracing Clojure/Script at some point, as that has much better chance of actually being useful. But I plan to keep circling around to Deuce until one can complete the Emacs tutorial. It's fun to hack on at times.

**Comment by hraberg** [comment]
Closing as this is mainly a question which has been answered.
I might work a bit on getting the Zile test suite to pass in August.
